### ISSUE TITLE
Running createNbCluster_paul has toggled my default cluster from 'netbatch' to 'local'...

### ISSUE THREAD

**Issue by pasafier** [nambar12/matlab_netbatch_scheduler#14]
Not sure why it's doing this. I made certain to set it to 'netbatch' before running the command. Then I got the warning below and checked and it had swapped back to 'local'.

>> createNbCluster_paul
Warning: The value of DefaultProfile is 'netbatch' which is not the name of an existing profile.  Setting
the DefaultProfile to 'local' at the user level.  Valid profile names are:
	'local' 'Processes' 'processes' 'Threads' 'threads'

**Comment by rsnorris** [comment]
We'll look at this during our next call.  createNbCluster should only be called once.  It's only job is to create the netbatch profile.
