### ISSUE TITLE
communicatingJobWrapperSmpd.sh: Fix environment variable

### ISSUE THREAD

**Issue by rsnorris** [nambar12/matlab_netbatch_scheduler#16]
Search for the following code

```
# Work out which port to use for SMPD
chooseSmpdPort() {
    # Use Netbatch's LSB_JOBID to calculate the port
    SMPD_PORT=`expr ${LSB_JOBID} % 10000 + 20000`
}
```

I'm guessing that Netbatch doesn't have LSB_JOBID.  Need to replace it with the Netbatch environment variable for the job ID.

**Comment by rsnorris** [comment]
Next, we need to resolve LSB_MCPU_HOSTS.

**Comment by nambar12** [comment]
opened issue to add SMPD support
