### ISSUE TITLE
Requesting 240 workers stalls out

### ISSUE THREAD

**Issue by pasafier** [nambar12/matlab_netbatch_scheduler#2]
When I run:

>> c = parcluster;
p = c.parpool(240)

Matlab hangs up in a perpetual starting up phase:

Starting parallel pool (parpool) using the 'netbatch' profile ...

And checking Netbatch shows that some cores have been allocated. In this case it seems to be 143:

athwor dlxcfe062
Run      639460166:239  "SLES12"                       /ptm/ipag            pasafier /nfs/site/eda/data/tcad0000/mathwor dlxcfg011
Run      639460166:240  "SLES12"                       /ptm/ipag            pasafier /nfs/site/eda/data/tcad0000/mathwor dlxcfg001
-----------------------------------------------------------------------------------------------------------------------------------------
                           WAITING queue is empty.
                          Number of RUNNING jobs: 143

What is the max amount of helpers I can request?
What determines this max?
Why did it give 143?
Should we have something in place such that if someone requests more cores than are available that the code just gives the max available, but doesn't hang up?

**Comment by nambar12** [comment]
Need to remove slots_per_host=2

**Comment by rsnorris** [comment]
This is a bug in MATLAB/MPI, not Netbatch.  MathWorks Development is aware of it and plans to have it resolved in a future version of MATLAB, as well as back ported to R2021a U8.  This can be closed.
