### ISSUE TITLE
Parallel pool failed to start

### ISSUE THREAD

**Issue by pasafier** [nambar12/matlab_netbatch_scheduler#21]
createNbCluster ran without issue, but starting the parpool failed with this message:

![image](https://user-images.githubusercontent.com/99370541/180260166-338f5b09-efe5-4983-894a-0cd1d2d279b2.png)

**Comment by pasafier** [comment]
Here's what the validation gave:

![image](https://user-images.githubusercontent.com/99370541/180262422-98fd77cc-cd71-4dd1-814a-2aeacab523b4.png)

**Comment by nambar12** [comment]
Does not reproduce
