### ISSUE TITLE
How to see how many workers/cores are in use for a batch job?

### ISSUE THREAD

**Issue by pasafier** [nambar12/matlab_netbatch_scheduler#3]
After running a batch job, checking what’s running with a netbatch command gives the following result, which just seems to show one thing running. 

How can I see (what Netbatch command) that it’s using the amount of workers I requested (48)?

![image](https://user-images.githubusercontent.com/99370541/153309622-2721451f-2fbb-4169-912f-1365c6aac186.png)

**Comment by pasafier** [comment]
Based on how long the particular test job is running, I do not think it's using the amount of workers c.Numworkers indicates... In a case I'm running today, c.Numworkers is 100, however, there is no way it's using 100 workers based on how long the code is taking...

**Comment by pasafier** [comment]
So, the code is going too long so I deleted the job from the Job Monitor. Netbatch still shows a machine as in use. How do I properly kill a batch job?

For reference, the batch job was started with the following commands:

theCode = 'Simple_Parallel_Code';
c = parcluster;
j = c.batch(theCode);
pause(5)
j.State

**Comment by rsnorris** [comment]
> Based on how long the particular test job is running, I do not think it's using the amount of workers c.Numworkers indicates... In a case I'm running today, c.Numworkers is 100, however, there is no way it's using 100 workers based on how long the code is taking...

c.NumWorkers simply states the maximum size of a parallel pool, because it's the number of MATAB Parallel Server licenses (purchased).  The way to set the size of the parallel pool is either with the parpool command (e.g., parpool(20)) or with the batch command (e.g., batch(..., 'Pool', 20) )

**Comment by pasafier** [comment]
Thanks. I was not using the proper command as it didn't explicitly stipulate the workers needed. So, I suppose I was just getting a single worker, which is why the job took forever to run.

I just updated the command to include 'Pool',(c.NumWorkers - 1) and now I can see with a netbatch command how many workers its using.

**Comment by rsnorris** [comment]
Paul wasn't calling batch() with the Pool argument.
