### ISSUE TITLE
Parpool Stayed Active beyond IdleTimeout Period

### ISSUE THREAD

**Issue by pasafier** [nambar12/matlab_netbatch_scheduler#9]
The parpool (140 workers) that we set up during our meeting Tuesday, is still active today (~47 hrs later).

![image](https://user-images.githubusercontent.com/99370541/158839808-0ea08c53-8b21-41d0-9cf9-54a45582e0fa.png)

**Comment by pasafier** [comment]
Note that Matlab was in a "frozen" state since we met--it was hung evaluating whatever command you had last typed. Control-C did not work to interrupt it, so I had to shut down the Matlab session. Upon opening a new session, I don't know how to release the machines that're held up. Typing delete(gcp('nocreate')) does not work in the new session.

**Comment by nambar12** [comment]
I see that jobs in Netbatch are completed

nbstatus jobs --target pasafier_matlab --fi '*,finishtime'
…
7:20  
     11:63 Comp            2          plxcag4009    SLES12&> /nfs/site/eda/data/tcad0000/mathwo> 7          03/17/2022 08:57:20  
     11:64 Comp            2          plxcag4004    SLES12&> /nfs/site/eda/data/tcad0000/mathwo> 7          03/17/2022 08:57:20  
…

They were not removed by Netbatch but rather though matlab . @pasafier  - was this the time that you've killed the session?

**Comment by pasafier** [comment]
Correct, I killed the Matlab session this morning (17th) just before 9AM PST.

**Comment by nambar12** [comment]
Ok, not sure if there is an issue then. We might add timeout on the Netbatch side for these pools. to kill the jobs after XX time of after XX time of inactivity to prevent waste of resources. Does this make sense?

**Comment by nambar12** [comment]
Need to set the parallel preferences to shutdown after 3 minutes. Matlab should delete the pool and remove the jobs

**Comment by nambar12** [comment]
testing this passed, closing the issue
